### PR TITLE
Add initial systemd binds repo

### PR DESCRIPTION
**Pull request by bernhardkaindl**
Hi @igo95862 feel free to start your own systemd binds or copy it for your own version.

I just wanted to make these initial binds available.

Best Regards,
Bernhard

### CODE REVIEW

**Comment by igo95862** [comment]
Thank you. My work on sdbus has been very slow in recent months. Still trying to finish the network manager binds version 2.0

BTW there are interfaces XML under `/usr/share/dbus-1/interfaces/` in a recent systemd versions.

**Comment by bernhardkaindl** [comment]
BTW: Releasing `python-sdbus-networkmanager` as a new release is not important for me as my CI/CD is now happily using a snapshot which works for me.

> BTW there are interfaces XML under /usr/share/dbus-1/interfaces/ in a recent systemd versions.

Yes, I've red about that. And tried it as well, but e.g. on Ubuntu 22.04 they are not even installed when installing `libsytemd-dev` which has `depends` on apparently all the other systemd packages.

I figured that the only drawback of getting the interfaces XML from the program itself is that it's not possible to use it when cross-building systemd for another architecture which is not the case when developing Systemd binds. In all other cases one can get the interfaces XML from the program all the time.

PS: For in case somebody would want to use `python-sdbus-systemd` bindings (even only as starting point),
it would be nice to merge this PR so it can be found more quickly.

**Comment by igo95862** [comment]
> Yes, I've red about that. And tried it as well, but e.g. on Ubuntu 22.04 they are not even installed when installing `libsytemd-dev` which has `depends` on apparently all the other systemd packages.

It is a very recent addition. (that I personally contributed to systemd)

On earlier versions you can use `--bus-introspect` option to print introspection.

`/usr/lib/systemd/systemd --bus-introspect=list` to list interfaces. `/usr/lib/systemd/systemd --bus-introspect=org.freedesktop.systemd1.Unit` to print specific interface.

**Comment by igo95862** [comment]
I pushed 93fb0bd7a26945a898224f82c2b9901e94e2041d where I added a new section "Community interfaces" to the README. Your systemd binds are the first addition.

**Comment by bernhardkaindl** [comment]
Thanks, closing.

**Pull request closed without merging**
